title: Anderson Gomes
suffix: Anderson Gomes
author: Anderson Gomes
keyword: Anderson Gomes
is_article_img: true  
web_description: 
home_layout: card
menus_title:
  home: HOME
  #archive: ARCHIVE
  #categories: CATEGORIES
  #tags: TAGS
  #links: LINKS
  about: ABOUT
menus:
  home: /
  #archive: /archives
  #categories: /categories
  #tags: /tags
  #links: /links
  about: /about
icon: /assets/favicons/favicon.ico
bottomIcon: 
  - {
    name: 'Github',
    iconLink: '/assets/images/github-mark.png',
    toUrl: 'https://github.com/andersongomes-dev/theme-andersongomes-dev'
  }
linksList:
  - {
      title: 'github',
      intro: 'GitHub é uma plataforma de hospedagem de código-fonte e arquivos com controle de versão usando o Git.',
      link: 'https://github.com/',
      image: '/assets/images/github-mark.png'
  }
